### ISSUE TITLE
Code Louisville Courses to be Completed

### ISSUE THREAD

**Issue by dke85** [dke85/treehouse#2]
## TODO

*Courses left to complete the Code Louisville track*

* [ ] GitHub Basics
* [ ] Responsive Layouts
* [ ] CSS Flexbox Layout
* [ ] HTML Forms
* [ ] Javascript Loops, Arrays, Objects
* [ ] Javascript and the DOM
* [ ] CSS Selectors
* [ ] jQuery Basics
* [ ] Bootstrap 4 Basics
* [ ] Web Accessibility Compliance
* [ ] Web Optimization

🥇 💯
